MySite/urls.py
import xadmin

from django.conf.urls.static import static,serve
from django.conf.urls import url, include
from django.views import static

from . import settings

urlpatterns = [
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'ueditor/', include('DjangoUeditor.urls')),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'', include('comments.urls', namespace='comments')),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

]


#定义404和500页面
handler404 = "blog.views.page_not_found"
handler500 = "blog.views.page_error"

apps/blog/urls.py
from django.conf.urls import url, include

from .views import IndexView,DetailView,CategoryView,ArticleListView,MoodListView,AboutView
urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^article_detail/(?P<article_id>\d+)/$', DetailView.as_view(), name="article_detail"),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name="category"),
    url(r'^article/$', ArticleListView.as_view(), name="article_list"),
    url(r'^mood_list/$', MoodListView.as_view(), name="mood_list"),
    url(r'^about/$', AboutView.as_view(), name="about"),



]

apps/comments/urls.py
from django.conf.urls import url, include

from .views import *
urlpatterns = [
    url(r'^comments/$', CommentView.as_view(), name="comment"),
    # url(r'^add_commnent/$', AddCommentView.as_view(), name="add_comment"),
    url(r'^add_comment/$',AddCommentView.as_view(), name='add_comment'),
]

extra_app/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/comments/models.py
from datetime import datetime

from django.db import models

# Create your models here.

class Comment(models.Model):

    comment_name = models.CharField(max_length=20, verbose_name="名字")
    text = models.CharField(max_length=200,default="", verbose_name="评论")
    is_show = models.CharField(choices=(('show','展示'),('notshow','不展示')),default='show',verbose_name="是否展示",max_length=20)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.text[:10]

# class Comments(models.Model):
#
#     comment_name = models.CharField(verbose_name='姓名', max_length=20, default='佚名')
#     text = models.CharField(verbose_name='内容', max_length=300)
#     add_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
#     class Meta:
#         verbose_name = '留言'
#         verbose_name_plural = verbose_name
#
#     def __str__(self):
#         return self.text[:10]



# class Comments(models.Model):
#     """
#     留言
#     """
#     name = models.CharField(default='',max_length=30, verbose_name="评论者名字")
#     comments = models.CharField(default='',max_length=200, verbose_name="评论")
#     add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")
#
#     class Meta:
#         verbose_name = "留言"
#         verbose_name_plural = verbose_name
#
#     def __str__(self):
#         return self.name

apps/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_name","text"]
        labels = {

        }

apps/comments/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.db.models.aggregates import Count
from django.http import HttpResponse

from pure_pagination import Paginator, PageNotAnInteger
from blog.models import Article, Category
from .models import Comment
from .forms import CommentForm

# Create your views here.

class CommentView(View):
    def get(self, request):
        article_num = Article.objects.count()  # 统计文章数量
        comment_num = Comment.objects.count()  # 统计评论数量
        read_article = Article.objects.all().order_by("read_num")[:10]  # 点击排行

        #   热门分类
        #  Count 计算分类下的文章数，其接受的参数为需要计数的模型的名称
        hot_category = Category.objects.annotate(num_articles=Count('article')).order_by('-num_articles')[:8]
        newest_article = Article.objects.all().order_by("-add_time")[:10]  # 最新发布

        #取出所有评论
        all_comment = Comment.objects.filter(is_show='show').order_by('-add_time')
        #对评论进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_comment, 10, request=request)
        comments = p.page(page)

        return render(request, 'comment.html',{
            'hot_category': hot_category,
            'newest_article': newest_article,
            'read_article': read_article,
            'article_num': article_num,
            'comment_num': comment_num,
            'all_comment': comments
        })


class AddCommentView(View):

    def post(self, request):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.save()
            return HttpResponse('{"status": "success"}', content_type='application/json')
        else:
            return HttpResponse('{"status": "fail"}', content_type='application/json')

extra_app/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_bread %}
    <ol class="breadcrumb w_breadcrumb">
      <li><a href="{% url 'blog:index' %}">首页</a></li>
      <li class="active">文章分享</li>
      <span class="w_navbar_tip">我们长路漫漫，只因学无止境。</span>
    </ol>{% endblock %}
{% block custom_left %}
    <div class="col-lg-9 col-md-9 w_main_left">
        <div class="panel panel-default">
            <div class="panel panel-default">

                <div class="panel-body">

            <!--文章列表开始-->
            <div class="contentList">
                {% for article in all_article.object_list %}
                <div class="panel panel-default">
                    <div class="panel-body">

                        <h4><a class="title" href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></h4>
                        <p>
                            <a class="label label-default">{{ article.category }}</a>
                        </p>
                        <p class="overView">{{ article.brief }}</p>
                        <p><span class="count"><i class="glyphicon glyphicon-user"></i><a href="#">{{ article.author }}</a></span> <span class="count"><i class="glyphicon glyphicon-eye-open"></i>阅读:{{ article.read_num }}</span><span class="count"><i class="glyphicon glyphicon-time"></i>{{ article.add_time }}</span></p>

                    </div>
                </div>
                {% endfor %}
            </div>
            <!--文章列表结束-->
            <!--分页功能-->
        <div class="pageturn">
            <ul class="pagelist">
            {#  如果有，获取上一页 #}
            {% if all_article.has_previous %}
            <li class="long"><a href="?{{ all_article.previous_page_number.querystring }}"
                                    class="page">上一页</a></li>
            {% endif %}

            {# 判断剩余页面的显示方法： #}
            {% for page in all_article.pages %}

                {% if page %}
                    {% ifequal page all_article.number %}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="none"><a href="">...</a></li>
                {% endif %}
            {% endfor %}

            {#  如果有，获取下一页 #}
            {% if all_article.has_next %}
                <li class="long"><a href="?{{ all_article.next_page_number.querystring }}">下一页</a></li>
            {% endif %}

        </ul>
    </div>
            <!--分页功能结束-->

        </div>
    </div>

        </div>
    </div>
{% endblock %}
{% block custom_right %}
    <div class="col-lg-3 col-md-3 w_main_right">
    <div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">站内搜索</h3>
							</div>
							<div class="panel-body">
								<div class="labelList">
                                    <form action="{% url 'blog:article_list' %}" class="parent">
                                    <input name="q" type="text" class="search" placeholder="请输入文章名或关键字" style="margin-left:-2px;">
                                    <button type="submit" class="search_btn"><span class="ion-ios-search-strong">搜索</span></button>
                                </form>
								</div>
							</div>
						</div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">热门标签</h3>
            </div>
            <div class="panel-body">
                <div class="labelList">
                    {% for category in hot_category %}
                    <a href="{% url 'blog:category' category.id %}" class="label label-default">{{ category.category_name }}({{ category.num_articles }})</a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">最新发布</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled sidebar">
                    {% for article in newest_article %}
                    <li>
                        <a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">点击排行</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled sidebar">
                    {% for article in read_article %}
                    <li>
                        <a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">站点信息</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled sidebar">
                    <li><strong>建站时间</strong>：2019-3-1</li>
                    <li><strong>网站主题</strong>：IT技术文章分享</li>
                    <li><strong>文章统计</strong>：{{ article_num }}篇</li>
                    <li><strong>文章评论</strong>：共{{ comment_num }}个</li>
                </ul>
            </div>
            <div class="panel-heading">
                <h3 class="panel-title">关注微信公众号</h3>
            </div>
            <div class="panel-body">
                <img src="{% static 'img/weixin.png' %}" style="height: 230.5px;width: 230.5px;" />
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">友情链接</h3>
            </div>
            <div class="panel-body">
                <div class="newContent">
                    <ul class="list-unstyled sidebar shiplink">
                        <li>
                            <a href="https://www.baidu.com/" target="_blank">百度</a>
                        </li>
                        <li>
                            <a href="https://www.oschina.net/" target="_blank">开源中国</a>
                        </li>
                        <li>
                            <a href="http://www.ulewo.com/" target="_blank">有乐网</a>
                        </li>
                        <li>
                            <a href="http://www.sina.com.cn/" target="_blank">新浪网</a>
                        </li>
                        <li>
                            <a href="http://www.qq.com/" target="_blank">腾讯网</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
{% endblock %}{#<!DOCTYPE html>#}

templates/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_bread %}
    <ol class="breadcrumb w_breadcrumb">
      <li><a href="{% url 'blog:index' %}">首页</a></li>
      <li class="active">文章详情</li>
      <span class="w_navbar_tip">学习与坐禅相似，须有一颗恒心。</span>
    </ol>{% endblock %}
{% block custom_left %}
    <div class="col-lg-9 col-md-9 w_main_left">
    <div class="panel panel-default">
        <div class="panel-body">
            <h2 class="c_titile" style="text-align: center">{{ article.title }}</h2>
            <p class="box_c" style="text-align: center;margin-top: 20px;color: #9c9c9c"><span class="d_time" style="left: 20px;">发布时间：{{ article.add_time }}</span><span style="margin-left: 20px;">编辑:{{ article.author }}</span><span style="margin-left: 20px;">阅读:{{ article.read_num }}</span></p>

                {% autoescape off %}
                {{ article.body }}
                {% endautoescape %}
        </div>
    </div>
</div>
{% endblock %}
{% block custom_right %}
    <div class="col-lg-3 col-md-3 w_main_right">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">热门标签</h3>
							</div>
							<div class="panel-body">
								<div class="labelList">
                                    {% for category in hot_category %}
									<a class="label label-default">{{ category.category_name }}({{ category.num_articles }})</a>
                                    {% endfor %}
								</div>
							</div>
						</div>

						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">点击排行</h3>
							</div>
							<div class="panel-body">
								<ul class="list-unstyled sidebar">
                                    {% for article in read_article %}
									<li>
										<a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a>
									</li>
                                    {% endfor %}
								</ul>
							</div>
						</div>

                        <div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">站点信息</h3>
							</div>
							<div class="panel-body">
								<ul class="list-unstyled sidebar">
                                    <li><strong>建站时间</strong>：2019-3-1</li>
                                    <li><strong>网站主题</strong>：IT技术文章分享</li>
                                    <li><strong>文章统计</strong>：{{ article_num }}篇</li>
                                    <li><strong>文章评论</strong>：共{{ comment_num }}个</li>
								</ul>
							</div>
							<div class="panel-heading">
								<h3 class="panel-title">关注微信公众号</h3>
							</div>
							<div class="panel-body">
								<img src="{% static 'img/weixin.png' %}" style="height: 230.5px;width: 230.5px;" />
							</div>
						</div>

						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">友情链接</h3>
							</div>
							<div class="panel-body">
								<div class="newContent">
									<ul class="list-unstyled sidebar shiplink">
										<li>
											<a href="https://www.baidu.com/" target="_blank">百度</a>
										</li>
										<li>
											<a href="https://www.oschina.net/" target="_blank">开源中国</a>
										</li>
										<li>
											<a href="http://www.ulewo.com/" target="_blank">有乐网</a>
										</li>
										<li>
											<a href="http://www.sina.com.cn/" target="_blank">新浪网</a>
										</li>
										<li>
											<a href="http://www.qq.com/" target="_blank">腾讯网</a>
										</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

	<head>
		<meta charset="UTF-8">
		<title>陈航个人博客</title>
	</head>

	<link href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}" />
    {% block custom_css %}{% endblock %}
	<link href="#" rel="shortcut icon" />
	<script src="{% static 'plugin/jquery.min.js' %}"></script>
	<script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/search.js' %}"></script>
    {% block custom_js %}{% endblock %}
	<!--<script type="text/javascript" src="plugin/jquery.page.js"></script>-->
	<!--<script src="js/common.js"></script>-->
	<!--<script src="js/snowy.js"></script>-->

	<body>
		<div class="w_header">
			<div class="container">
				<div class="w_header_top">
					<a href="#" class="w_logo"></a>
					<span class="w_header_nav">
                        <ul>
                            <li><a href="{% url 'blog:index' %}" {% if request.path == '/' %}class="active"{% endif %}>首页</a></li>
                            <li><a href="{% url 'blog:article_list' %}" {% if request.path|slice:'8' == '/article' %}class="active"{% endif %}>文章分享</a></li>
                            <li><a href="{% url 'blog:about' %}" {% if request.path|slice:'6' == '/about' %}class="active"{% endif %}>我&网站</a></li>
    {#						<li><a href="">娱乐</a></li>#}
                            <li><a href="{% url 'blog:mood_list' %}"{% if request.path|slice:'10' == '/mood_list' %}class="active"{% endif %}>时间轴</a></li>
                            <li><a href="{% url 'comments:comment' %}" {% if request.path|slice:'9' == '/comments' %}class="active"{% endif %}>给我留言</a></li>
                        </ul>
				    </span>
				</div>
			</div>
		</div>
		<div class="w_container">
			<div class="container">
				<div class="row w_main_row">
                    {% block custom_bread %}{% endblock %}

                    {% block custom_left %}{% endblock %}
					<!--左侧开始-->
                    {% block custom_right %}{% endblock %}
				</div>
			</div>
		</div>
	</body>
    <div class="w_foot">
        <div class="w_foot_copyright">Copyright &copy; 2017-2020, www.wfyvv.com. All Rights Reserved. <span>|</span>
            <a target="_blank" href="http://www.miitbeian.gov.cn/" rel="nofollow">皖ICP备17002922号</a>
        </div>
		</div>
<script type="text/javascript">
    var $backToTopEle = $('<a href="javascript:void(0)" class="Hui-iconfont toTop" title="返回顶部" alt="返回顶部" style="display:none">^</a>').appendTo($("body")).click(function() {
        $("html, body").animate({ scrollTop: 0 }, 120);
    });
    var backToTopFun = function() {
        var st = $(document).scrollTop(),
            winh = $(window).height();
        (st > 0) ? $backToTopEle.show(): $backToTopEle.hide();
        /*IE6下的定位*/
        if(!window.XMLHttpRequest) {
            $backToTopEle.css("top", st + winh - 166);
        }
    };

    $(function() {
        $(window).on("scroll", backToTopFun);
        backToTopFun();
    });
</script>

</html>

templates/moodList.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_bread %}
    <ol class="breadcrumb w_breadcrumb">
      <li><a href="{% url 'blog:index' %}">首页</a></li>
      <li class="active">时间轴</li>
      <span class="w_navbar_tip">时光飞逝，机会就在我们眼前，何时找到了灵感，就要把握机遇，我们需要智慧和勇气去把握机会。</span>
    </ol>
{% endblock %}

{% block custom_left %}
<div class="container">
    <div class="timebox">
        <ul id="list" style="list-style: none;">
            {% for article in all_article.object_list %}
                <li><span>{{ article.add_time|date:"Y-m-d" }}</span><a href="{% url 'blog:article_detail' article.id %}" title="{{ article.title }}">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
<ol class="breadcrumb w_breadcrumb bottombread">
      <li><a href="#"></a></li>
      <li class="active"></li>
      <span class="w_navbar_tip"></span>
</ol>
    <div class="pageturn">
            <ul class="pagelist">
            {#  如果有，获取上一页 #}
            {% if all_article.has_previous %}
            <li class="long"><a href="?{{ all_article.previous_page_number.querystring }}"
                                    class="page">上一页</a></li>
            {% endif %}

            {# 判断剩余页面的显示方法： #}
            {% for page in all_article.pages %}

                {% if page %}
                    {% ifequal page all_article.number %}
                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="none"><a href="">...</a></li>
                {% endif %}
            {% endfor %}

            {#  如果有，获取下一页 #}
            {% if all_article.has_next %}
                <li class="long"><a href="?{{ all_article.next_page_number.querystring }}">下一页</a></li>
            {% endif %}

        </ul>
    </div>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <P>12345</P>
</body>
</html>